baseURL = 'https://killarexe.github.io/Copper-Extension-wiki'
languageCode = 'en-us'
title = 'Copper Extension Wiki'

defaultContentLanguage = "en"

[markup.goldmark.renderer]
  unsafe = true

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"
    disable = false

[params]
  [params.navbar]
    displayTitle = true
    displayLogo = true
  [params.footer]
    enable = false
    displayPoweredBy = false
    displayCopyright = false
  [params.highlight.copy]
    enable = true
    display = "hover"

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
  [languages.fr]
    languagesName = "Fran√ßais"
    weight = 20

[menu]
  [[menu.main]]
    name = "Modrinth"
    url = "https://modrinth.com/mod/copper-extension"
    weight = 10
  [[menu.main]]
    name = "Curseforge"
    url = "https://modrinth.com/mod/copper-extension"
    weight = 20
  [[menu.main]]
    name = "Github"
    url = "https://modrinth.com/mod/copper-extension"
    weight = 30
    params = { icon = "github" }
